# Generated by Django 4.1.5 on 2023-06-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='photo',
            field=models.ImageField(upload_to='store_app/image'),
        ),
    ]
