# Generated by Django 4.1.5 on 2023-06-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_authormodel_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='store_app/image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.authormodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.bookmodel')),
            ],
        ),
    ]
